### ISSUE TITLE
Alteração do position da classe joint-paper

### ISSUE THREAD

**Issue by adriano2606** [brmodeloweb/brmodelo-docs#2]
Atualmente o position da classe joint-paper está como 'relative' e quando o usuário insere uma entidade no canvas, o objeto de entidade acaba subindo na posição e ficando atrás do header da página.

É interessante para a correção do bug alterar o `position` da classe `.joint-paper` para `absolute`, conforme vídeos anexos.

https://github.com/brmodeloweb/brmodelo-docs/assets/96502994/39539925-5775-45d6-8b38-146c3dfae854

https://github.com/brmodeloweb/brmodelo-docs/assets/96502994/3c897121-f783-4f97-989f-ef15ee6cef15

**Comment by idmarjr** [comment]
Oi @adriano2606 !

Muito obrigado por reportar o problema com tantos detalhe, incluindo videos pra demonstrar o problema e uma possível solução!

O merge request https://github.com/brmodeloweb/brmodelo-app/pull/545 pra resolver esse problema.  
Optei por uma solução um pouco diferente da que você propôs pra não mostrar `support-banners-list` quando a janela é tem menos que `620px` de altura. Dessa forma evitamos que os banners de supporte fiquem sobre os elementos da sidebar em qualquer situação.

No merge request tem mais detalhes se você quiser ir mais a fundo.

Mais uma vez, muito obrigado por reportar o problema e ajudar a gente a fazer o BRMW melhor 💟   
Da próxima vez, fica a vontade pra fazer um fork e abrir um merge request com a proposta de solução! que trabalhamos nisso juntos :)
